### ISSUE TITLE
Keep integration.

### ISSUE THREAD

**Issue by piotrfonte** [meedan/montage#42]
This is a integration task picking up on the front-end work done in `feature/keep` branch of this repo ( https://github.com/meedan/montage/tree/feature/keep) and documented as part of `montage-components` repo in the following issues:

- https://github.com/meedan/montage-components/issues/20
- https://github.com/meedan/montage-components/issues/1
- https://github.com/meedan/montage-components/issues/2
- https://github.com/meedan/montage-components/issues/3
- https://github.com/meedan/montage-components/issues/5
- https://github.com/meedan/montage-components/issues/6

# Please find below the complete list of elements and directives to be wired:

- [x] Project List Item: https://github.com/meedan/montage/blob/feature/keep/appengine/src/greenday_public/static-dev/js/components/project/project-list-item.directive.js#L195-L224 that corresponds to this `montage-components` issue: https://github.com/meedan/montage-components/issues/1
- [ ] Keep Settings modal accessible from the Topbar when in a Project: https://github.com/meedan/montage/blob/feature/keep/appengine/src/greenday_public/static-dev/js/services/dialog.service.js#L269-L297 that corresponds to this `montage-components` issue: https://github.com/meedan/montage-components/issues/5
- [ ] Keep status flags in the Videos table: *1.* Pass down model information to display appropriate status flag here: https://github.com/meedan/montage/blob/feature/keep/appengine/src/greenday_public/static-dev/js/components/gd-video-list/gd-video-list-item.html#L33-L52 *2.* wire up the directive: https://github.com/meedan/montage/blob/feature/keep/appengine/src/greenday_public/static-dev/js/components/gd-video-list/gd-video-list-item.directive.js#L23-L30 — especially error case should trigger a Toast with `Retry` as call to action. This corresponds to the following `montage-components` issue: https://github.com/meedan/montage-components/issues/2
- [ ] Keep status flags on the Video page: *1.* Pass down model info to display appropriate flag: https://github.com/meedan/montage/blob/feature/keep/appengine/src/greenday_public/static-dev/js/components/gd-video-details-panel/gd-video-details-panel.html#L59-L70 *2.* Wire the directive respectively: https://github.com/meedan/montage/blob/feature/keep/appengine/src/greenday_public/static-dev/js/components/gd-video-details-panel/gd-video-details-panel.directive.js#L216-L238 and an error Toast in particular displaying call to action to Retry. This picks up on this `montage-components` issue: https://github.com/meedan/montage-components/issues/6

I hope to have left enough comments in the code to support all requirements, but should anything be unclear, or I’ve used some erroneous patterns to add the front-end bits—please let me know. I’m happy to get back to it anytime and make necessary amends.

**Comment by infojunkie** [comment]
Thanks @piotrf for the great details. We'll review the requirements and the code and get back to you if anything is unclear.

**Comment by infojunkie** [comment]
Implementation note: we plan to call the Keep API from the frontend directly, to avoid extensive modifications to the Montage backend. However, one modification we will need to do is to add a "Keep" setting to the Project data model that stores the data from https://github.com/meedan/montage-components/issues/1

**Comment by infojunkie** [comment]
I updated the `feature/keep` branch with initial backend support for Keep:

- Pender (aka Keep) service is added to Docker Compose and Travis build files
- Pender settings (host and key) are exposed to both backend and frontend
- `Project` model has a new `project_settings` JSON attribute that is currently used to hold Keep settings
- `Project.project_settings` is wired into @piotrf 's frontend code in the Project List Item - I updated the TODO above accordingly

**Comment by infojunkie** [comment]
But it's looking less likely we'll be able to invoke Keep from the frontend. For example, adding 50 videos to a project that has Keep enabled with 2 archivers would require today 100 HTTP requests to be issued to Keep from the browser, which is a recipe for disaster. We can try to salvage the idea by creating a bulk request endpoint that would accept multiple URLs to be archived.

**Comment by danielafeitosa** [comment]
Needed on Keep:
- As Karim already commented, new endpoint that accepts multiple URLs
- New endpoint to retry the archive in a specific service. Keep always sends the URL to `archive.is` and `archive.org`.
- To allow the retry, Keep should also notify when the service return some archiving error. Keep only notifies the webhook when the URL is archived.

Needed on Montage:
- A webhook URL to be notified when Keep archive the URL
- Each video needs to store the Keep info for each service. It could be done with a JSON field on Video object, like `{archive_org: {location: <link_to_archived>}, archive_is: {location: <link_to_archived>}}`
- The Keep status flag should display the status and the `Retry` option for each service (Archive.is, Archive.org) enabled on project. Issues: meedan/montage-components#2 and meedan/montage-components#6

**Comment by infojunkie** [comment]
Thanks Daniela. We'll work on Keep-side functionality first then integrate into Montage.
